# Generated by Django 5.0.6 on 2024-06-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_alter_recipe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, height_field=100, upload_to='img/%Y/%m/%d/', width_field=100),
        ),
    ]
