# Generated by Django 5.0.6 on 2024-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0005_alter_recipe_options_alter_ingredient_quantity_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='', width_field=100),
        ),
    ]
