# Generated by Django 5.0.6 on 2024-07-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0006_alter_recipe_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
    ]
