# Generated by Django 5.0.6 on 2024-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0007_alter_recipe_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity_kg',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
