# Generated by Django 5.0.6 on 2024-07-01 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0008_remove_ingredient_quantity_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 7, 1)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateField(default=datetime.date(2024, 7, 1)),
        ),
    ]
