# Generated by Django 5.0.6 on 2024-07-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0013_ingredient_measure_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(choices=[('U', 'шт.'), ('G', 'гр.'), ('B', 'ст.л.'), ('S', 'чай.л.'), ('M', 'мл.')], default='гр.', max_length=1),
        ),
    ]
